name: Build extension

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build and package extension
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        ghidra:
          - "11.3.1"
          - "11.2"
          - "11.1.2"
          - "11.0.3"
          - "10.4"
          - "10.3.3"

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.ghidra <= '11.1.2' && '17' || '21' }}

    - name: Install Ghidra
      uses: antoniovazquezblanco/setup-ghidra@v2.0.5
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Update extension properties
      run: |
        echo "name=@extname@" > extension.properties
        echo "description=PlayStation(R)Vita ELF-PRX loader for Ghidra" >> extension.properties
        echo "author=CreepNT" >> extension.properties
        date +"createdOn=%Y/%m/%d" >> extension.properties
        echo "version=@extversion@" >> extension.properties

    - name: Build extension
      run: gradle -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VitaLoader Redux for Ghidra ${{ matrix.ghidra }}
        path: dist/ghidra_*_VitaLoaderRedux.zip
        if-no-files-found: warn
