name: Build extension

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build and package extension
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
        ghidra:
          - "11.0"
          - "10.4"
          - "10.3.3"
          - "10.3.2"
          - "10.3.1"
          - "10.3"

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Ghidra
      uses: antoniovazquezblanco/setup-ghidra@v1.2.0
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.11.1

    - name: Update extension properties
      run: |
        echo "name=@extname@" > extension.properties
        echo "description=PlayStation®Vita ELF-PRX loader for Ghidra" >> extension.properties
        echo "author=CreepNT" >> extension.properties
        date +"createdOn=%Y/%m/%d" >> extension.properties
        echo "version=@extversion@" >> extension.properties

    - name: Build extension
      run: ./gradlew -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VitaLoader Redux
        path: dist/ghidra_*_VitaLoaderRedux.zip
        if-no-files-found: warn
